Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from .views import UpdatePostView

urlpatterns = [
#     blogs
    path("home", views.blogs, name="blogs"),
    path("",views.index, name="index"),
    path("blog/<str:slug>/", views.blogs_comments, name="blogs_comments"),
    path("add_blogs/", views.add_blogs, name="add_blogs"),
    path("edit_blog_post/<str:slug>/", UpdatePostView.as_view(), name="edit_blog_post"),
    path("delete_blog_post/<str:slug>/", views.Delete_Blog_Post, name="delete_blog_post"),
    path("search/", views.search, name="search"),

    
#     profile
    path("profile/", views.Profile, name="profile"),
    path("user_profile/<int:myid>/", views.user_profile, name="user_profile"),
    
#    user authentication
    path("register/", views.Register, name="register"),
    path("login/", views.Login, name="login"),
    path("logout/", views.Logout, name="logout"),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.timezone import now


class BlogPost(models.Model):
    title=models.CharField(max_length=255)
    author= models.ForeignKey(User, on_delete=models.CASCADE)
    slug=models.CharField(max_length=130)
    content=models.TextField()
    image = models.ImageField(upload_to="profile_pics", blank=True, null=True)
    dateTime=models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return str(self.author) +  " Blog Title: " + self.title
    

    def get_absolute_url(self):
        return reverse('blogs')
    

    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    blog = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)   
    dateTime=models.DateTimeField(default=now)


    def __str__(self):
        return self.user.username +  " Comment: " + self.content
    

class user(models.Model):
    uuser = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    ufname = models.ImageField(upload_to="profile_pics", blank=True, null=True)
    ulanem = models.TextField(blank=True, null=True)
    umail = models.IntegerField(blank=True, null=True)
    upwd = models.CharField(max_length=300, blank=True, null=True)
    upwd2 = models.CharField(max_length=300, blank=True, null=True)
    uida = models.CharField(max_length=300, blank=True, null=True)
    
    def __str__(self):
        return str(self.user)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to="profile_pics", blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    phone_no = models.IntegerField(blank=True, null=True)
    facebook = models.CharField(max_length=300, blank=True, null=True)
    instagram = models.CharField(max_length=300, blank=True, null=True)
    linkedin = models.CharField(max_length=300, blank=True, null=True)
    
    def __str__(self):
        return str(self.user)

home/forms.py
from django import forms
from .models import Profile, BlogPost

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone_no', 'bio', 'facebook', 'instagram', 'linkedin', 'image', )
     
        
class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title', 'slug', 'content', 'image')
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Title of the Blog'}),
            'slug': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Copy the title with no space and a hyphen in between'}),
            'content': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Content of the Blog'}),
        }
    
class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title', 'slug', 'content', 'image')
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control',}),
            'slug': forms.TextInput(attrs={'class':'form-control', }),
            'content': forms.Textarea(attrs={'class':'form-control', }),
        }

home/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,  login, logout
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm, BlogPostForm, UpdatePostForm
from django.views.generic import UpdateView
from django.contrib import messages


def index(request):
    return render(request, "index.html")


def blogs(request):
    posts = BlogPost.objects.all()
    posts = BlogPost.objects.filter().order_by('-dateTime')
    return render(request, "blog.html", {'posts': posts})


def blogs_comments(request, slug):
    post = BlogPost.objects.filter(slug=slug).first()
    comments = Comment.objects.filter(blog=post)
    if request.method == "POST":
        user = request.user
        content = request.POST.get('content', '')
        blog_id = request.POST.get('blog_id', '')
        comment = Comment(user=user, content=content, blog=post)
        comment.save()
    return render(request, "blog_comments.html", {'post': post, 'comments': comments})


def Delete_Blog_Post(request, slug):
    posts = BlogPost.objects.get(slug=slug)
    if request.method == "POST":
        posts.delete()
        return redirect('/home')
    return render(request, 'delete_blog_post.html', {'posts': posts})


def search(request):
    if request.method == "POST":
        searched = request.POST['searched']
        if(len(searched) != 0):
            blogs = BlogPost.objects.filter(title__contains=searched)
            if(len(blogs)!=0):
                return render(request, "search.html", {'searched': searched, 'blogs': blogs})
            return redirect('/home')
        else:
            return redirect('/home')
    else:
        return render(request, "search.html", {})


@login_required(login_url='/login')
def add_blogs(request):
    if request.method == "POST":
        form = BlogPostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            blogpost = form.save(commit=False)
            blogpost.author = request.user
            blogpost.save()
            obj = form.instance
            alert = True
            return render(request, "add_blogs.html", {'obj': obj, 'alert': alert})
    else:
        form = BlogPostForm()
    return render(request, "add_blogs.html", {'form': form})

# class UpdatePostView(UpdateView):
#     model = BlogPost
#     template_name = 'edit_blog_post.html'
#     fields = ['title', 'slug', 'content', 'image']


class UpdatePostView(UpdateView):
    model = BlogPost
    form_class = UpdatePostForm
    template_name = 'edit_blog_post.html'


def user_profile(request, myid):
    post = BlogPost.objects.filter(id=myid)
    return render(request, "user_profile.html", {'post': post})


def Profile(request):
    return render(request, "profile.html")


def Register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 != password2:
            messages.error(request, "Passwords do not match.")
            # return redirect('/register')
            alert = True
            return render(request, "register.html", {'alert': alert})

        user = User.objects.create_user(username, email, password1)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        return render(request, 'login.html')
    return render(request, "register.html")


def Login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, "Successfully Logged In")
            return redirect("/home")
        else:
            messages.error(request, "Invalid Credentials")
            # return render(request, 'blog.html')
            alert = True
            return render(request, "login.html", {'alert': alert})
    return render(request, "login.html")


def Logout(request):
    logout(request)
    messages.success(request, "Successfully logged out")
    return redirect('/')

home/templates/add_blogs.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock %}
{% block add_blogs_active %} active {% endblock add_blogs_active %}

{% block css %}
.gradient-custom {
    background: rgb(0,0,0);
    background: linear-gradient(360deg, rgba(0,0,0,1) 0%, rgba(63,0,97,1) 20%, rgba(255,255,255,1) 100%);
}
{% endblock %}
{% block body %}
<section class="gradient-custom vh-100">
    <div class="container-fluid pt-4 ">
        <form action="/add_blogs/" enctype="multipart/form-data" method="POST"> {% csrf_token %}
            <div class="container flexbox mt-4 fw-bold">
                <p><label for="id_title" class="text-white">Title:</label> {{ form.title }} </p>
                <p><label for="id_slug" class="text-white">Slug:</label> {{ form.slug }} </p>
                <label for="id_slug" class="text-white">Content:</label>
                <textarea name="content" cols="40" rows="10" class="form-control" placeholder="Content of the Blog"
                    required="" id="id_content"></textarea>
                <p></p>
                <p><label for="id_image" class="text-white">Image:  {{ form.image }} </p>
                <button class="btn btn-dark">Add Blog</button>  
            </div>
        </form>
    </div>
</section>
{% endblock %}
{% block js %}
<script>
    {% if alert %}
    document.location = '/home';
    {% endif %}
</script>
{% endblock %}

home/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title> {% block title %} {% endblock %} </title>

  <style>
    .gradient-navbar {
      background: rgb(0,0,0);
background: radial-gradient(circle, rgba(0,0,0,1) 0%, rgba(50,2,77,1) 0%, rgba(0,0,0,1) 100%);
    }

    .gradient-custom {
      background: rgb(0,0,0);
background: radial-gradient(circle, rgba(0,0,0,1) 0%, rgba(50,2,77,1) 0%, rgba(0,0,0,1) 100%);
    }

    .btn-dark {
      background-color: black;
    }

    .bg-info {
      background-color: black !important;
      color: white !important;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg sticky-top gradient-navbar navbar-dark">
    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top"> -->
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Unwritten</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="d-flex mx-3">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% block homeactive %} {% endblock homeactive %}" aria-current="page"
                href="/home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% block add_blogs_active %} {% endblock add_blogs_active %}" href="/add_blogs/">Add
                Blogs</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="p4">
        <form class="d-flex" method="POST" action="/search/"> {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Type here to find a blog" name="searched"
            id="searched" aria-label="Search">
          <button href="/search/" class="btn btn-outline-secondary" type="submit">Search</button>
        </form>
      </div>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0 pl-4">
        <li class="nav-item">
          <a class="nav-link fw-bold text-light" href="/logout/">Log Out</a>
        </li>
      </ul>

      {% else %}
      <li class="nav-item">
        <a class="nav-link  " href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% block registeractive %} {% endblock registeractive %}" href="/register/">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% block loginactive %} {% endblock loginactive %}" href="/login/">Login</a>
      </li>
      </ul>
      {% endif %}
    </div>
    </div>
    </div>
  </nav>
  {% block body %}
  {% endblock %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script> -->
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  {% block js %}
  {% endblock %}
</body>

</html>

home/templates/blog.html
{% extends 'base.html' %}

{% block title %} Blogs {% endblock %}
{% block homeactive %} active {% endblock homeactive %}

{% block css %}

{% endblock %}
{% block body %}

{% if posts|length > 3 %}
<section class="gradient-custom p-4">
  {%else%}
  <section class="gradient-custom vh-100 p-4">
    {% endif %}
    <!-- <section class="gradient-custom vh-100"> -->
    <div class="container mt-5 mb-3">
      <div class="row">
        {% for post in posts %}
        <div class="col-lg-4 my-4">
          <div class="card shadow bg-info" style="width: 20rem; height: 33rem;">
            <!-- <img src="/media/{{post.image}}" class="card-img-top" alt="..." height="250px"> -->
            {% if post.image %}
            <img src="/media/{{post.image}}" class="card-img-top" alt="..." height="250px">
            {%else%}
            <img src="/media/blog_image.jpg" class="card-img-top" alt="..." height="250px">
            {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{post.title}}</h5>
              <h6><small class="text-white-50 pl-2"> - {{post.author}}</small></h6>
              <p class="card-text">{{post.content| truncatechars:210}}</p>
            </div>
            <a href="/blog/{{post.slug}}" class="btn btn-dark">Read More</a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
  {% endblock %}
  {% block js %}
  <script></script>
  {% endblock %}

home/templates/blog_comments.html
{% extends 'base.html' %}

{% block title %} Blogs {% endblock %}

{% block css %}
{% endblock %}
{% block body %}
{% load humanize %}
<section class="gradient-custom p-4">
      <div class="container w-50 my-4">
            <h1 class="blog-post-title text-white">{{post.title}}</h1>
            <div class="media">
                  <div class="media-body">
                        <h6 class="ml-4 fst-italic fw-light text-white"> - {{post.author}}</h6>
                        <h6 class="ml-4 fst-italic fw-light text-white"> {{post.dateTime}}</h6>
                        {% if user.is_authenticated %}
                        {% if user.id == post.author.id %}
                        <div class="d-flex flex-row-reverse fst-bold">
                              <small><a href="/delete_blog_post/{{post.slug}}/"
                                          class="edit btn btn-danger p-2 ml-2 ">Delete
                                          Post</a></small>
                              <small><a href="/edit_blog_post/{{post.slug}}/" class="edit btn btn-warning p-2">Edit
                                          Post</a></small>
                        </div>
                        {% endif %}
                        {% endif %}
                  </div>
            </div>
            <br>
            {% if post.image %}
            <img src="/media/{{post.image}}" alt="..." height="250px">
            {%else%}
            <img src="/media/blog_image.jpg" alt="..." height="250px">
            {% endif %}
            <br>
            <br>
            <p class="text-white">{{post.content}}.</p>
            <hr>
            {% if user.is_authenticated %}
            <div class="container">
                  <form action="/blog/{{post.slug}}/" method="POST"> {% csrf_token %}
                        <div class="form-floating">
                              <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2"
                                    style="height: 100px" id="content" name="content"></textarea>
                              <label for="floatingTextarea2">Leave a comment here.</label>
                              <br>
                              <button type="submit" class="btn btn-dark">Post Comment</button>
                        </div>
                  </form>
                  {% else %}
                  <div class="container">
                        <h4 class="text-white"><a href="/login/" class="text-">Login</a> to post comments below.</h4>
                        {% endif %}
                        <br>
                        <h2 class="text-white">All Comments ({{comments.count}})</h2>
                        <br>
                        {% for comment in comments %}
                        <div class="card">
                              <div class="card-header">
                                    <span style="font-size: 22px;">{{comment.user}} </span> <span
                                          style="font-size: 12px;">{{comment.dateTime | naturaltime}}</span>
                              </div>
                              <div class="card-body">
                                    <h6 class="card-text">{{comment.content}}</h6>
                              </div>
                        </div>
                        <br>
                        {% endfor %}
                  </div>
            </div>
      </div>
</section>

{% endblock %}

home/templates/delete_blog_post.html
{% extends 'base.html' %}

{% block title %} Delete Blog Post {% endblock %}

{% block css %}
{% endblock %}
{% block body %}
<section class="gradient-custom vh-100">
  <div class="container">
    <div class="p-3">
      <h3 class="mt-4 text-white">NOTE:</h3>
      <br>
      <h6 class="text-white"> This action has it's consequences, proceed with caution !</h6>
      <br>
      <h6 class="text-white"> Once deleted, blogs are thrown into the abyss !</h6>
      <br>
      <h6 class="text-white"> This action cannot be revoked !</h6>
    </div>

    <form enctype="multipart/form-data" method="POST"> {% csrf_token %}
      <div class="container mt-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Are you sure you want to delete this blog?</h5>
            <form action="/delete_blog_post/{{posts.slug}}/" method="POST">
              {% csrf_token %}
              <a href="/blog/{{posts.slug}}" class="btn btn-success">Cancel</a>
              <button class="btn btn-danger">Delete Blog</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</section>
{% endblock %}

home/templates/edit_blog_post.html
{% extends 'base.html' %}

{% block title %} Edit Blog Post {% endblock %}

{% block css %}
{% endblock %}
{% block body %}

<section class="gradient-custom vh-100">
    <div class="container-fluid pt-4">
        <form enctype="multipart/form-data" method="POST"> {% csrf_token %}
            <div class="container mt-4 fw-bold">
                <p><label for="id_title" class="text-white">Title:</label> {{ form.title }} </p>
                <p><label for="id_slug" class="text-white">Slug:</label> {{ form.slug }} </p>
                <label for="id_content" class="text-white">Content:</label>
                <p>{{form.content}}</p>
                <p></p>
                <p><label for="id_image" class="text-white">Image:{{ form.image }}</p>
                <button class="btn btn-dark" class="text-white">Update Blog</button>
            </div>
        </form>
    </div>
</section>

{% endblock %}

home/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title> {% block title %} {% endblock %} </title>

    <style>
        body {
            background-image: url('../media/haha.png');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }

        header {
            height: 125vh;
            width: 100%;
            color: white;
            font: bold 6.5em/2em monospace;
            display: flex;
            justify-content: center;
            align-items: center;
            background: linear-gradient(to top, black 30%, #9907facc);
        }
    </style>
</head>

<body>
    <header class="d-flex">
        <div class="bg align-items-center">
            <div class="container d-flex text-center">
                <div class="text-white">
                    <h1 class="mt-4 pt-4">UNWRITTEN</h1>
                    <h6 class="">A World To Be Written | A World To Be Explored</h6>
                    <h6><a class="btn btn-outline-light btn-lg"
                    href="/home" role="button">Visit Unwritten</a></h6>
                    <a class="btn btn-outline-light btn-lg{% block registeractive %} {% endblock registeractive %}"
                        href="/register/" role="button">Register</a>
                    <a class="btn btn-outline-light btn-lg {% block loginactive %} {% endblock loginactive %}"
                        href="/login/" role="button">Login</a>
                        <h5>
                            Developed By :
                        </h5>
                        <h6>
                            Janaki Jonah Alex Hazel
                        </h6>
                        <h6 class="fst-italic">
                            Build Battlers
                        </h6>
                </div>
            </div>
        </div>
    </header>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script> -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</body>

</html>

home/templates/login.html
{% extends 'base.html' %}

{% block title %} Login Page {% endblock %}
{% block loginactive %} active {% endblock loginactive %}

{% block css %}
.gradient-custom {
  background: rgb(6,0,9);
  background: linear-gradient(90deg, rgba(6,0,9,1) 0%, rgba(102,8,105,1) 49%, rgba(0,0,0,1) 100%);
}
{% endblock %}
{% block body %}

<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-info text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <form action="/login/" method="POST"> {% csrf_token %}
              <div class="mb-md-5 mt-md-4 pb-5">
                <h2 class="fw-bold mb-2 text-uppercase">UNWRITTEN</h2>
                <p class="text-white-50 mb-5">Login to Blog !</p>
                <div class="form-outline form-white mb-4">
                  <input type="text" class="form-control form-control-lg" id="username" name="username" required>
                  <label class="form-label" for="username">Username</label>
                </div>
                <div class="form-outline form-white mb-4">
                  <input type="password" class="form-control form-control-lg" id="password" name="password" required>
                  <label class="form-label" for="password">Password</label>
                </div>
                <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
              </div>
            </form>
            <div>
              <p class="mb-0">Don't have an account? <a href="/register/" class="text-white-50 fw-bold"> Sign Up</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% block js %}
<script>
    {% if alert %}
    alert('CHECK CREDENTIALS');
    document.location = '/login';
    {% endif %}
</script>
{% endblock %}
{% endblock %}

home/templates/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock %}
{% block profileactive %} active {% endblock profileactive %}

{% block css %}
.profile{
padding: 3%;
margin-top: 3%;
margin-bottom: 3%;
border-radius: 0.5rem;
background: #fff;
}
.profile-img{
text-align: center;
}
.profile-img .file {
position: relative;
overflow: hidden;
margin-top: -20%;
width: 70%;
border: none;
border-radius: 0;
font-size: 15px;
background: #212529b8;
}

{% endblock %}
{% block body %}

<div class="container profile">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    
                    <img src="{{user.profile.image.url}}" alt="" width="310px" height="270px">
                    
                </div>
            </div>
            <div class="col-md-8">
                <div class="profile-tab">
                    <div class="tab-pane">
                        <br><br>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Username:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Full Name:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user.get_full_name}}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user.email}}</p>
                            </div>
                        </div>
                        {% if user.profile.phone_no %}
                        <div class="row">
                            <div class="col-md-6">
                                <label>Phone Number:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user.profile.phone_no}}</p>
                            </div>
                        </div>
                        {% endif %}
                        {% if user.profile.bio %}
                        <div class="row">
                            <div class="col-md-6">
                                <label>Bio:</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{user.profile.bio}}</p>
                            </div>
                        </div>
                        {% endif %}
                        {% if user.profile.linkedin %}
                        <div class="row">
                            <div class="col-md-6">
                                <label>Linkedin:</label>
                            </div>
                            <div class="col-md-6">
                                <p><a href="{{user.profile.linkedin}}">{{user.profile.linkedin}}</a></p>
                            </div>
                        </div>
                        {% endif %}
                        {% if user.profile.instagram %}
                        <div class="row">
                            <div class="col-md-6">
                                <label>Instagram:</label>
                            </div>
                            <div class="col-md-6">
                                <p><a href="{{user.profile.instagram}}">{{user.profile.instagram}}</a></p>
                            </div>
                        </div>
                        {% endif %}
                        {% if user.profile.facebook %}
                        <div class="row">
                            <div class="col-md-6">
                                <label>Facebook:</label>
                            </div>
                            <div class="col-md-6">
                                <p><a href="{{user.profile.facebook}}">{{user.profile.facebook}}</a></p>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    <a href="/edit_profile/" class="btn btn-secondary">Edit Profile</a>
                </div>
            </div>
</div>
</div>
{% endblock %}